#!/bin/sh
set -e
./gradlew publishKotlinMavenPublicationToMavenCentralRepository
./gradlew publishPluginMavenPublicationToMavenCentralRepository
./gradlew publishKotlinMavenPublicationToGithubRepository || true
./gradlew publishPluginMavenPublicationToGithubRepository || true
./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET || true
