#!/bin/sh
set -e
TO_CENTRAL='./gradlew publishAllPublicationsToMavenCentralRepository --parallel'
TO_GH='./gradlew publishAllPublicationsToGithubRepository --parallel'
$TO_CENTRAL || $TO_CENTRAL || $TO_CENTRAL || $TO_CENTRAL || $TO_CENTRAL
$TO_GH || true
