/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("multiproject.kotlin-application-conventions")
    id("org.danilopianini.multi-jvm-test-plugin")
    id("org.danilopianini.publish-on-central")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("multiproject.app.AppKt")
}
