/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.danilopianini.publish-on-central")
    id("multiproject.kotlin-library-conventions")
    id("org.danilopianini.multi-jvm-test-plugin")
}
