import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    const val com_gradle_plugin_publish_gradle_plugin: String =
            "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin:" +
            Versions.com_gradle_plugin_publish_gradle_plugin

    const val com_palantir_git_version_gradle_plugin: String =
            "com.palantir.git-version:com.palantir.git-version.gradle.plugin:" +
            Versions.com_palantir_git_version_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * http://www.github.com/kotlintest/kotlintest */
    const val kotlintest_runner_junit5: String = "io.kotlintest:kotlintest-runner-junit5:" +
            Versions.kotlintest_runner_junit5

    const val org_danilopianini_publish_on_central_gradle_plugin: String =
            "org.danilopianini.publish-on-central:org.danilopianini.publish-on-central.gradle.plugin:" +
            Versions.org_danilopianini_publish_on_central_gradle_plugin

    const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" +
            Versions.org_jetbrains_dokka_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin
}
