name: CI Guard
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  pr-guard:
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.repository
      || startsWith(github.head_ref, 'refs/heads/dependabot/')
    steps:
      - run: 'true'
  ci-cd:
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit
